/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Cliente;
import Modelo.ServicioClientes;
import java.util.List;
import javax.swing.JTextArea;

/**
 *
 * @author isaac
 */
public class FrmHistorico extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmHistorico
     */
    public FrmHistorico(ServicioClientes servicioClientes) {
        initComponents(); 
         mostrarHistorico(servicioClientes);
    }
    
      private void mostrarHistorico(ServicioClientes servicioClientes) {
        List<Cliente> historico = servicioClientes.getHistoricoClientes();

        if (historico.isEmpty()) {
            TextArea.setText("No hay clientes eliminados.");
            return;
        }

        StringBuilder sb = new StringBuilder();
        for (Cliente cliente : historico) {
            sb.append("ID: ").append(cliente.getId()).append("\n")
              .append("Nombre: ").append(cliente.getNombre()).append("\n")
              .append("Correo: ").append(cliente.getCorreo()).append("\n")
              .append("Teléfono: ").append(cliente.getTelefono()).append("\n")
              .append("Preferente: ").append(cliente.isPreferente() ? "Sí" : "No").append("\n")
              .append("--------------------------\n");
        }

        TextArea.setText(sb.toString());
    }  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();

        setClosable(true);
        setFocusable(false);

        TextArea.setEditable(false);
        TextArea.setBackground(new java.awt.Color(255, 255, 255));
        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
