/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.GestorClientesMem;
import Modelo.IGestorClientes;
import Modelo.ServicioClientes;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author jprod
 */
public class FrmMain extends javax.swing.JFrame {
    private ServicioClientes servicioClientes;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMain.class.getName());

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        dtpMenu = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuAdmin = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        Historicomenubar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dtpMenuLayout = new javax.swing.GroupLayout(dtpMenu);
        dtpMenu.setLayout(dtpMenuLayout);
        dtpMenuLayout.setHorizontalGroup(
            dtpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1029, Short.MAX_VALUE)
        );
        dtpMenuLayout.setVerticalGroup(
            dtpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        menuAdmin.setText("Administrar");
        menuAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        menuAdmin.add(menuClientes);

        menuBar.add(menuAdmin);

        Historicomenubar.setText("Historial");
        Historicomenubar.setToolTipText("");

        jMenuItem1.setText("Elimacion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Historicomenubar.add(jMenuItem1);

        menuBar.add(Historicomenubar);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
       IGestorClientes gestor = new GestorClientesMem();
       servicioClientes = new ServicioClientes(gestor);
       FrmClientes frm = new FrmClientes(servicioClientes);
       this.dtpMenu.add(frm);
       frm.setVisible(true);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
         if (servicioClientes == null) {
        JOptionPane.showMessageDialog(this, "Debe abrir primero el módulo de Clientes.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Evitar abrir múltiples veces el mismo internal frame
    for (JInternalFrame frame : dtpMenu.getAllFrames()) {
        if (frame instanceof FrmHistorico) {
            try {
                frame.setSelected(true);
            } catch (java.beans.PropertyVetoException ex) {
            }
            return;
        }
    }

    FrmHistorico frame = new FrmHistorico(servicioClientes);
    dtpMenu.add(frame);
    frame.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
   
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Historicomenubar;
    private javax.swing.JDesktopPane dtpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuClientes;
    // End of variables declaration//GEN-END:variables
}
